# Generated by Django 3.1 on 2020-09-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=30)),
                ('normal_price', models.FloatField(max_length=30)),
                ('offer_price', models.FloatField(max_length=30)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
        ),
    ]
