# Generated by Django 3.1 on 2020-10-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
