# Generated by Django 3.1 on 2020-10-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201027_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='normal_price',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
