# Generated by Django 3.1 on 2020-11-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201118_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.typeprice')),
            ],
        ),
    ]
